<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d38bcb65-1d97-4b83-a8f5-ad88840e3749</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRplatform.Application\HRplatform.Application.csproj" />
    <ProjectReference Include="..\HRplatform.Domain\HRplatform.Domain.csproj" />
    <ProjectReference Include="..\HRplatform.Infrastructure\HRplatform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
